language: c
compiler:
  - arm-linux-none-eabi-g++
install:
  - sudo apt-get install g++-arm-linux-gnueabi
addons:
  apt:
    sources:
      - george-edison55-precise-backports # cmake 3.2.3 / doxygen 1.8.3
    packages:
      - cmake
      - cmake-data
script:
  - make

